


# ________________________________________________________________________________
# DEAFULT
# ________________________________________________________________________________
.PHONY: clean into


default:
	gcc exercise_4_2.c -o main
	./main
	xxxd text.tmp

info:
	gcc -v

clean:
	rm -rf *.elf
	rm -rf *.tmp




# ________________________________________________________________________________
# CHAPTER 4
# ________________________________________________________________________________
exercise_4_1.elf: exercise_4_1.c
	gcc exercise_4_1.c -o exercise_4_1.elf
	./exercise_4_1.elf test.tmp


exercise_4_2.elf: exercise_4_2.c
	gcc exercise_4_2.c -o exercise_4_2.elf
	# ./exercise_4_2.elf test.tmp


