


# ________________________________________________________________________________
# DEAFULT
# ________________________________________________________________________________
.PHONY: clean into


default:
	gcc exercise_5_x.c -o main
	./main

info:
	gcc -v

clean:
	rm -rf *.elf
	rm -rf *.tmp




# ________________________________________________________________________________
# CHAPTER 5
# ________________________________________________________________________________
exercise_5_2: exercise_5_2.c
	gcc exercise_5_2.c -o exercise_5_2.elf
	# ./exercise_4_2.elf test.tmp

exercise_5_3: exercise_5_3.c
	gcc exercise_5_3.c -o exercise_5_3.elf


