


# ________________________________________________________________________________
# INFO
# ________________________________________________________________________________
info:
	git version  # 2.17.1

.PHONY: init clean exec

exec:
	chmod +x *.bash

init: clean
	bash init.bash

clean:
	rm -rf .git
	rm -rf *.c
	rm -rf *.patch
	rm -rf *.orig
	rm -rf *.rej


