

# ________________________________________________________________________________
# DEFAULT
# ________________________________________________________________________________


.PHONY: info

info:
	#openssl ecparam -genkey -name secp256r1 
	#openssl ec -out ec.key -aes128
	#openssl genrsa -aes128 -out fd.key 2048
	#openssl rsa -text -in fd.key
	openssl rsa -in fd.key -pubout -out fd-public.key